# Generated by Django 3.2.9 on 2021-12-26 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0032_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 14, 6, 5, 646974)),
        ),
    ]
