# Generated by Django 3.2.9 on 2022-01-01 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0042_auto_20211231_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ship_add_user',
            new_name='shippingAddress_user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 16, 28, 1, 200970)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='primeflix_app.order'),
        ),
    ]
