# Generated by Django 3.2.9 on 2022-01-01 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0045_auto_20220101_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 18, 56, 54, 39874)),
        ),
    ]
