# Generated by Django 3.2.9 on 2022-01-06 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0048_auto_20220102_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='orderLine_user',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 17, 21, 31, 779894)),
        ),
    ]
