# Generated by Django 3.2.9 on 2022-01-09 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0050_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 12, 57, 54, 627468)),
        ),
    ]
